@startuml
namespace people {
    class Person << (S,Aquamarine) >> {
        + Name string
        + X int
        + Renderer *render.ActorRenderer

        + UpdateRenderAll(enabled bool) 
        + UpdateRenderPos() 
        + UpdateVisibility(visible bool) 

    }
}


namespace render {
    class ActorRenderer << (S,Aquamarine) >> {
        + Sheet *pixel.Picture
        + FrameIndex int
        + ChunkX int
        + X int
        + Visible bool

        - makeKey() string
        - makeChunkIndex() int

        + AddSprite(key string) 
        + RemoveSprite(key string) 
        + UpdateVisibility(visible bool) 
        + UpdatePos(x int, y int, z int) 

    }
    class Chunk << (S,Aquamarine) >> {
        - changed bool

        + MaxHeight int
        + WorldData *[][][]int
        + W int

        + CalculateMax() 
        + SetChanged(changed bool) 
        + GetChanged() bool

    }
}


@enduml
